title: "Science Hindi"
description: "हिंदी में करियर, शिक्षा और सरकारी नौकरियों की पूरी जानकारी"
url: "https://sciencehindi.in"   # Your full domain
baseurl: ""   
theme: minima

permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

# ADD THIS ENTIRE BLOCK TO YOUR _config.yml

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

# Author info
author:
  name: "Singh Codes"
  image: "/assets/images/myprofilepic.webp"

logo: /assets/images/logo.png # The path to your site's logo for Schema

twitter:
  username: Sciencehindi  # Your username without the '@'

social:
  name: Science Hindi          # Your brand name for social media
  links:
    - https://twitter.com/YourTwitterHandle
    - https://www.facebook.com/YourFacebookPage
    # You can add more links here (e.g., LinkedIn, Instagram)


# Exclude unnecessary files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

defaults:
  -
    scope:
      path: "" # Applies to the whole site
    values:
      sitemap: true # This is the default setting, but is safe to keep
  -
    scope:
      path: ""
      type: "posts" # Applies default values ONLY to posts
    values:
      # It's better to use a relative URL for the default image
      image: "/assets/images/myprofilepic.webp"
      author: "Singh Codes"
      lang: "hi"

# Feed setting (optional, this is the default value)
feed:
  path: feed.xml
