title: "Science Hindi"
description: "हिंदी में करियर, शिक्षा और सरकारी नौकरियों की पूरी जानकारी"
url: "https://sciencehindi.in"   # Your full domain
baseurl: ""   
theme: minima

permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

# ADD THIS ENTIRE BLOCK TO YOUR _config.yml

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

# Author info
author:
  name: "Singh Codes"
  image: "/assets/images/myprofilepic.JPG"

# Exclude unnecessary files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Sitemap settings (jekyll-sitemap works automatically, but we can set priority)
defaults:
  -
    scope:
      path: ""
    values:
      sitemap: true

# Feed settings
feed:
  path: feed.xml

# SEO defaults
defaults:
  - scope:
      path: ""   # applies to whole site
      type: "posts"
    values:
      image: "https://sciencehindi.in/assets/images/default-og.jpg"
      author: "Singh Codes"
      lang: "hi"   # Hindi content
