title: "My Blog"
description: "A simple Jekyll blog on GitHub Pages"
url: "https://sciencehindi.in"   # Your full domain
baseurl: ""   
theme: minima

permalink: /:title/

plugins:
  - jekyll-sitemap
